In [81]:
import numpy as np
arr = np.arange(6)
print("Array:", arr)
print("Data type:", arr.dtype)

Array: [0 1 2 3 4 5]
Data type: int64


In [82]:
import numpy as np

arr = np.array([1.5, 2.6, 3.7])

print("Array:", arr)
print("Data type:", arr.dtype)

# check dtype
if arr.dtype == np.float64:
    print("The array is of type float64")
else:
    print("The array is NOT of type float64")

Array: [1.5 2.6 3.7]
Data type: float64
The array is of type float64


In [83]:
import numpy as np

# create array of complex numbers
arr = np.array([2+3j, 4+5j, 6+7j], dtype=np.complex128)

print("Array:", arr)
print("Data type:", arr.dtype)

Array: [2.+3.j 4.+5.j 6.+7.j]
Data type: complex128


In [84]:
import numpy as np

# integer array
arr = np.array([1, 2, 3, 4, 5])
print("Original array:", arr)
print("Original dtype:", arr.dtype)

# convert to float32
arr_float = arr.astype(np.float32)
print("Converted array:", arr_float)
print("Converted dtype:", arr_float.dtype)

Original array: [1 2 3 4 5]
Original dtype: int64
Converted array: [1. 2. 3. 4. 5.]
Converted dtype: float32


In [85]:
import numpy as np

# float64 array
arr = np.array([1.123456789, 2.987654321, 3.141592653589], dtype=np.float64)

print("Original array:", arr)
print("Original dtype:", arr.dtype)

# convert to float32
arr_float32 = arr.astype(np.float32)

print("Converted array:", arr_float32)
print("Converted dtype:", arr_float32.dtype)

Original array: [1.12345679 2.98765432 3.14159265]
Original dtype: float64
Converted array: [1.1234568 2.9876542 3.1415927]
Converted dtype: float32


In [86]:
import numpy as np

def array_attributes(arr):
    """
    Returns the shape, size, and data type of a NumPy array.
    """
    return arr.shape, arr.size, arr.dtype


# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float32)

shape, size, dtype = array_attributes(arr)

print("Shape:", shape)
print("Size:", size)
print("Data type:", dtype)

Shape: (2, 3)
Size: 6
Data type: float32


In [87]:
import numpy as np

def array_dimension(arr):
    """
    Returns the dimensionality (number of dimensions) of a NumPy array.
    """
    return arr.ndim

In [88]:
import numpy as np

def array_dimension(arr):
    """
    Returns the dimensionality (number of dimensions) of a NumPy array.
    """
    return arr.ndim
arr1 = np.array([1, 2, 3])          # 1D array
arr2 = np.array([[1, 2], [3, 4]])   # 2D array
arr3 = np.array([[[1], [2]], [[3], [4]]])  # 3D array

print("Dimensionality of arr1:", array_dimension(arr1))
print("Dimensionality of arr2:", array_dimension(arr2))
print("Dimensionality of arr3:", array_dimension(arr3))

Dimensionality of arr1: 1
Dimensionality of arr2: 2
Dimensionality of arr3: 3


In [89]:
import numpy as np
# question no 9

def array_strides(arr):
    """
    Returns the strides of a NumPy array.
    """
    return arr.strides


# Example usage
arr1 = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
arr2 = np.array([[1.0, 2.0], [3.0, 4.0]], dtype=np.float64)

print("Strides of arr1:", array_strides(arr1))
print("Strides of arr2:", array_strides(arr2))

Strides of arr1: (12, 4)
Strides of arr2: (16, 8)


In [90]:
import numpy as np

def shape_stride_relationship(arr):
    """
    Returns the shape and strides of a NumPy array.
    """
    return arr.shape, arr.strides


# Example usage
arr1 = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
arr2 = np.array([[1.0, 2.0], [3.0, 4.0]], dtype=np.float64)

shape1, strides1 = shape_stride_relationship(arr1)
shape2, strides2 = shape_stride_relationship(arr2)

print("Array 1 -> Shape:", shape1, " | Strides:", strides1)
print("Array 2 -> Shape:", shape2, " | Strides:", strides2)

Array 1 -> Shape: (2, 3)  | Strides: (12, 4)
Array 2 -> Shape: (2, 2)  | Strides: (16, 8)


In [91]:
import numpy as np

def create_zeros_array(n):
    """
    Returns a NumPy array of zeros with n elements.
    """
    return np.zeros(n)


# Example usage
arr = create_zeros_array(5)
print("Zeros Array:", arr)
print("Shape:", arr.shape)
print("Data type:", arr.dtype)

Zeros Array: [0. 0. 0. 0. 0.]
Shape: (5,)
Data type: float64


In [92]:
import numpy as np

def create_ones_matrix(rows, cols):
    """
    Returns a 2D NumPy array (matrix) of ones with shape (rows, cols).
    """
    return np.ones((rows, cols))


# Example usage
matrix = create_ones_matrix(3, 4)
print("Ones Matrix:\n", matrix)
print("Shape:", matrix.shape)
print("Data type:", matrix.dtype)

Ones Matrix:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Shape: (3, 4)
Data type: float64


In [93]:
import numpy as np

def generate_range_array(start, stop, step):
    """
    Returns a NumPy array starting from 'start',
    ending before 'stop', with a step size of 'step'.
    """
    return np.arange(start, stop, step)


# Example usage
arr = generate_range_array(2, 10, 2)
print("Generated Array:", arr)
print("Shape:", arr.shape)
print("Data type:", arr.dtype)

Generated Array: [2 4 6 8]
Shape: (4,)
Data type: int64


In [94]:
import numpy as np

def generate_linear_space(start, stop, num):
    """
    Returns a NumPy array with 'num' equally spaced values
    between 'start' and 'stop' (inclusive).
    """
    return np.linspace(start, stop, num)


# Example usage
arr = generate_linear_space(0.0, 1.0, 5)
print("Generated Array:", arr)
print("Shape:", arr.shape)
print("Data type:", arr.dtype)

Generated Array: [0.   0.25 0.5  0.75 1.  ]
Shape: (5,)
Data type: float64


In [95]:
import numpy as np

def create_identity_matrix(n):
    """
    Returns an n x n identity matrix using NumPy.
    """
    return np.eye(n)


# Example usage
matrix = create_identity_matrix(4)
print("Identity Matrix:\n", matrix)
print("Shape:", matrix.shape)
print("Data type:", matrix.dtype)


Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Shape: (4, 4)
Data type: float64


In [96]:
import numpy as np

def list_to_numpy_array(py_list):
    """
    Converts a Python list into a NumPy array.
    """
    return np.array(py_list)


# Example usage
my_list = [1, 2, 3, 4, 5]
arr = list_to_numpy_array(my_list)

print("Original List:", my_list)
print("NumPy Array:", arr)
print("Data type:", arr.dtype)

Original List: [1, 2, 3, 4, 5]
NumPy Array: [1 2 3 4 5]
Data type: int64


In [97]:
import numpy as np

# Create an original array
arr = np.array([10, 20, 30, 40, 50], dtype=np.int32)

# Create a view of the array
arr_view = arr.view()

print("Original Array:", arr)
print("View Array:", arr_view)

# Modify the view
arr_view[2] = 99

print("\nAfter modifying the view:")
print("Original Array:", arr)
print("View Array:", arr_view)


Original Array: [10 20 30 40 50]
View Array: [10 20 30 40 50]

After modifying the view:
Original Array: [10 20 99 40 50]
View Array: [10 20 99 40 50]


In [98]:
import numpy as np

def concatenate_arrays(arr1, arr2, axis=0):

    return np.concatenate((arr1, arr2), axis=axis)


# Example usage
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Concatenate along axis 0 (rows)
result1 = concatenate_arrays(a, b, axis=0)

# Concatenate along axis 1 (columns)
result2 = concatenate_arrays(a, b, axis=1)

print("Concatenate along axis 0:\n", result1)
print("Concatenate along axis 1:\n", result2)

Concatenate along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenate along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


In [99]:
import numpy as np

# First array with shape (2, 2)
arr1 = np.array([[1, 2],
                 [3, 4]])

# Second array with shape (2, 3)
arr2 = np.array([[5, 6, 7],
                 [8, 9, 10]])

# Concatenate horizontally (axis=1)
result = np.concatenate((arr1, arr2), axis=1)

print("Array 1:\n", arr1)
print("Array 2:\n", arr2)
print("\nConcatenated Array (Horizontal):\n", result)

Array 1:
 [[1 2]
 [3 4]]
Array 2:
 [[ 5  6  7]
 [ 8  9 10]]

Concatenated Array (Horizontal):
 [[ 1  2  5  6  7]
 [ 3  4  8  9 10]]


In [100]:
import numpy as np

def vertical_stack_arrays(arr_list):

    return np.vstack(arr_list)


# Example usage
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
c = np.array([[7, 8]])

result = vertical_stack_arrays([a, b, c])

print("Array A:\n", a)
print("Array B:\n", b)
print("Array C:\n", c)
print("\nVertically Stacked Array:\n", result)

Array A:
 [[1 2]
 [3 4]]
Array B:
 [[5 6]]
Array C:
 [[7 8]]

Vertically Stacked Array:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [101]:
import numpy as np

def create_range_array(start, stop, step=1):

    return np.arange(start, stop + 1, step)
arr1 = create_range_array(1, 10, 2)
arr2 = create_range_array(5, 20, 3)

print("Array 1:", arr1)
print("Array 2:", arr2)

Array 1: [1 3 5 7 9]
Array 2: [ 5  8 11 14 17 20]


In [102]:
import numpy as np

def generate_equal_spaced_array():

    return np.linspace(0, 1, 10)


# Example usage
arr = generate_equal_spaced_array()
print("Equally spaced array:", arr)

Equally spaced array: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [103]:

def generate_log_spaced_array():

    return np.logspace(0, 3, 5)  # exponents 0 to 3, 5 values


# Example usage
arr = generate_log_spaced_array()
print("Logarithmically spaced array:", arr)

Logarithmically spaced array: [   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [104]:
import numpy as np
import pandas as pd

def create_random_dataframe():

    data = np.random.randint(1, 101, size=(5, 3))  # 5x3 array of random ints
    df = pd.DataFrame(data, columns=["Col1", "Col2", "Col3"])
    return df













In [105]:
df = create_random_dataframe()
print(df)

   Col1  Col2  Col3
0    77     9     8
1    20    93    33
2    24    86    19
3    90    37    28
4    29     6    61


In [106]:
import numpy as np
import pandas as pd

def replace_negative_with_zero(df, column):

    df[column] = np.where(df[column] < 0, 0, df[column])
    return df


# Example usage
data = {
    "A": [10, -5, 20, -15, 30],
    "B": [7, 14, -21, 28, -35]
}
df = pd.DataFrame(data)

print("Original DataFrame:\n", df)

# Replace negatives in column 'A'
df = replace_negative_with_zero(df, "A")

print("\nDataFrame after replacing negatives in column A:\n", df)


Original DataFrame:
     A   B
0  10   7
1  -5  14
2  20 -21
3 -15  28
4  30 -35

DataFrame after replacing negatives in column A:
     A   B
0  10   7
1   0  14
2  20 -21
3   0  28
4  30 -35


In [107]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Access 3rd element (index = 2)
third_element = arr[2]

print("Array:", arr)
print("3rd Element:", third_element)


Array: [10 20 30 40 50]
3rd Element: 30


In [108]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# element at (1, 2)
element = arr[1, 2]

print("Array:\n", arr)
print("Element at (1, 2):", element)


Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at (1, 2): 6


In [109]:
import numpy as np

arr = np.array([3, 8, 2, 10, 5, 7])

# Boolean indexing -> elements > 5
result = arr[arr > 5]

print("Original Array:", arr)
print("Elements greater than 5:", result)



Original Array: [ 3  8  2 10  5  7]
Elements greater than 5: [ 8 10  7]


In [110]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Slice from index 2 to 5 (inclusive → so we take stop=6)
result = arr[2:6]

print("Original Array:", arr)
print("Elements from index 2 to 5:", result)


Original Array: [1 2 3 4 5 6 7 8 9]
Elements from index 2 to 5: [3 4 5 6]


In [111]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Slice rows 0:2 and columns 1:3
sub_array = arr[0:2, 1:3]

print("Original Array:\n", arr)
print("\nSub-array:\n", sub_array)


Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Sub-array:
 [[2 3]
 [5 6]]


In [112]:
import numpy as np

def extract_elements(arr, indices):
    """
    Extract elements from a 2D array in a specific order
    based on indices provided in another array.

    Parameters:
        arr (ndarray): Input 2D NumPy array
        indices (ndarray): Indices of elements to extract

    Returns:
        ndarray: Extracted elements
    """
    return np.take(arr, indices)


# Example usage
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

# Indices of elements in flatt


In [113]:
import numpy as np

def filter_greater_than(arr, threshold):
    """
    Filters elements greater than a threshold from a 1D NumPy array.

    Parameters:
        arr (ndarray): Input 1D NumPy array
        threshold (int/float): Threshold value

    Returns:
        ndarray: Elements greater than threshold
    """
    return arr[arr > threshold]


# Example usage
arr = np.array([3, 8, 1, 10, 5, 7])
result = filter_greater_than(arr, 5)

print("Original Array:", arr)
print("Filtered Elements (greater than 5):", result)


Original Array: [ 3  8  1 10  5  7]
Filtered Elements (greater than 5): [ 8 10  7]


In [114]:
import numpy as np

def extract_from_3d(arr, idx0, idx1, idx2):
    """
    Extracts specific elements from a 3D NumPy array
    using indices provided in three separate arrays.

    Parameters:
        arr (ndarray): Input 3D NumPy array
        idx0 (ndarray/list): Indices for axis 0
        idx1 (ndarray/list): Indices for axis 1
        idx2 (ndarray/list): Indices for axis 2

    Returns:
        ndarray: Extracted elements
    """
    return arr[idx0, idx1, idx2]


# Example usage
arr = np.arange(1, 28).reshape(3, 3, 3)  # 3x3x3 array

# Indices for each axis
idx0 = [0, 1, 2]   # layer index
idx1 = [1, 2, 0]   # row index
idx2 = [2, 1, 0]   # column index

result = extract_from_3d(arr, idx0, idx1, idx2)

print("3D Array:\n", arr)
print("\nExtracted Elements:", result)


3D Array:
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

Extracted Elements: [ 6 17 19]


In [115]:
import numpy as np

def filter_with_two_conditions(arr, cond1, cond2):
    """
    Returns elements from arr where both conditions are satisfied.

    Parameters:
        arr (ndarray): Input NumPy array
        cond1 (ndarray/bool expression): First condition
        cond2 (ndarray/bool expression): Second condition

    Returns:
        ndarray: Filtered elements
    """
    return arr[cond1 & cond2]


# Example usage
arr = np.array([3, 8, 12, 5, 18, 7, 20])

# Condition 1: greater than 5
# Condition 2: even numbers
result = filter_with_two_conditions(arr, arr > 5, arr % 2 == 0)

print("Original Array:", arr)
print("Filtered Elements ( >5 and even):", result)


Original Array: [ 3  8 12  5 18  7 20]
Filtered Elements ( >5 and even): [ 8 12 18 20]


In [116]:
import numpy as np

def extract_from_2d(arr, row_indices, col_indices):
    """
    Extracts elements from a 2D NumPy array using row and column indices.

    Parameters:
        arr (ndarray): Input 2D NumPy array
        row_indices (list/ndarray): Row indices
        col_indices (list/ndarray): Column indices

    Returns:
        ndarray: Extracted elements
    """
    return arr[row_indices, col_indices]


# Example usage
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

rows = np.array([0, 1, 2])   # row indices
cols = np.array([2, 1, 0])   # column indices

result = extract_from_2d(arr, rows, cols)

print("Original Array:\n", arr)
print("Row indices:", rows)
print("Column indices:", cols)
print("Extracted Elements:", result)


Original Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Row indices: [0 1 2]
Column indices: [2 1 0]
Extracted Elements: [30 50 70]


In [117]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

result = arr + 5
print(result)


[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [118]:
import numpy as np

arr1 = np.array([[2, 3, 4]])     # shape (1, 3)
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9,10,11,12]])  # shape (3, 4)

result = arr2 * arr1.T
print(result)


[[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


In [119]:
import numpy as np

arr1 = np.array([[1, 2, 3, 4]])   # shape (1, 4)
arr2 = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90],
                 [100,110,120]])  # shape (4, 3)

result = arr2 + arr1.T
print(result)


[[ 11  21  31]
 [ 42  52  62]
 [ 73  83  93]
 [104 114 124]]


In [120]:
import numpy as np

arr1 = np.array([[1],
                 [2],
                 [3]])   # shape (3,1)

arr2 = np.array([[10, 20, 30]])  # shape (1,3)

result = arr1 + arr2
print(result)


[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [121]:
import numpy as np

# Q40
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr2 = np.array([[2, 3],
                 [4, 5]])
arr2_broadcasted = np.hstack([arr2, arr2[:, [0]]])
result_40 = arr1 * arr2_broadcasted
print(result_40)


[[ 2  6  6]
 [16 25 24]]


In [122]:
# Q41
arr = np.array([[1, 2, 3], [4, 5, 6]])
result_41 = arr.mean(axis=0)
print(result_41)


[2.5 3.5 4.5]


In [123]:
# Q43
arr = np.array([[1, 2, 3], [4, 5, 6]])
result_43 = arr.argmax(axis=0)
print(result_43)


[1 1 1]


In [124]:
# Q44
arr = np.array([[1, 2, 3], [4, 5, 6]])
def moving_sum(row):
    return np.cumsum(row)
result_44 = np.apply_along_axis(moving_sum, axis=1, arr=arr)
print(result_44)


[[ 1  3  6]
 [ 4  9 15]]


In [125]:
# Q45
arr = np.array([[1, 2, 3], [4, 5, 6]])
result_45 = np.all(arr % 2 == 0, axis=0)
print(result_45)


[False False False]


In [126]:
# Q46
import numpy as np
original_array = np.array([1, 2, 3, 4, 5, 6])
m, n = 2, 3
result_46 = original_array.reshape(m, n)
print(result_46)


[[1 2 3]
 [4 5 6]]


In [127]:
# Q47
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
def flatten_matrix(matrix):
    return matrix.flatten()
result_47 = flatten_matrix(input_matrix)
print(result_47)


[1 2 3 4 5 6]


In [128]:
# Q48
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
def concat_arrays(a1, a2, axis):
    return np.concatenate((a1, a2), axis=axis)
result_48 = concat_arrays(array1, array2, axis=0)
print(result_48)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [129]:
# Q49
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
def split_array(arr, sections, axis):
    return np.split(arr, sections, axis=axis)
result_49 = split_array(original_array, 3, axis=0)
print(result_49)


[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [130]:
# Q50
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]
arr_inserted = np.insert(original_array, indices_to_insert, values_to_insert)
arr_deleted = np.delete(arr_inserted, indices_to_delete)
print(arr_inserted)
print(arr_deleted)


[ 1  2 10  3  4 11  5]
[ 1 10  4 11  5]


In [131]:
# Q51
arr1 = np.random.randint(1, 10, size=10)
arr2 = np.arange(1, 11)
result_51 = arr1 + arr2
print(arr1)
print(arr2)
print(result_51)


[9 3 9 9 8 6 6 4 2 9]
[ 1  2  3  4  5  6  7  8  9 10]
[10  5 12 13 13 12 13 12 11 19]


In [132]:
# Q52
arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)
result_52 = arr1 - arr2
print(arr1)
print(arr2)
print(result_52)


[10  9  8  7  6  5  4  3  2  1]
[ 1  2  3  4  5  6  7  8  9 10]
[ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [133]:
# Q53
arr1 = np.random.randint(1, 10, size=5)
arr2 = np.arange(1, 6)
result_53 = arr1 * arr2
print(arr1)
print(arr2)
print(result_53)


[5 8 1 4 3]
[1 2 3 4 5]
[ 5 16  3 16 15]


In [134]:
# Q54
arr1 = np.arange(2, 11, 2)
arr2 = np.arange(1, 6)
result_54 = arr1 / arr2
print(arr1)
print(arr2)
print(result_54)


[ 2  4  6  8 10]
[1 2 3 4 5]
[2. 2. 2. 2. 2.]


In [135]:
# Q55
arr1 = np.arange(1, 6)
arr2 = arr1[::-1]
result_55 = np.power(arr1, arr2)
print(arr1)
print(arr2)
print(result_55)


[1 2 3 4 5]
[5 4 3 2 1]
[ 1 16 27 16  5]


In [136]:
# Q56
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
def count_substring(arr, substring):
    return np.char.count(arr, substring)
result_56 = count_substring(arr, 'hello')
print(result_56)


[1 0 1 0 1]


In [137]:
# Q57
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
def extract_uppercase(arr):
    return [ ''.join([ch for ch in s if ch.isupper()]) for s in arr ]
result_57 = extract_uppercase(arr)
print(result_57)


['H', 'W', 'OAI', 'GPT']


In [138]:
# Q58
import numpy as np
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
def replace_substring(arr, old, new):
    return np.char.replace(arr, old, new)
result_58 = replace_substring(arr, 'apple', 'mango')
print(result_58)


['mango' 'banana' 'grape' 'pinemango']


In [139]:
# Q59
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
def concat_strings(a1, a2):
    return np.char.add(a1, a2)
result_59 = concat_strings(arr1, arr2)
print(result_59)


['HelloOpen' 'WorldAI']


In [140]:
# Q60
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
def longest_length(arr):
    return max(np.char.str_len(arr))
result_60 = longest_length(arr)
print(result_60)


9


In [141]:
# Q61
data = np.random.randint(1, 1001, size=100)
mean = np.mean(data)
median = np.median(data)
variance = np.var(data)
std_dev = np.std(data)
print(mean, median, variance, std_dev)


465.74 482.0 93948.13239999999 306.5095959346134


In [142]:
# Q62
data = np.random.randint(1, 101, size=50)
p25 = np.percentile(data, 25)
p75 = np.percentile(data, 75)
print(p25, p75)


23.0 73.75


In [143]:
# Q63
x = np.random.randint(1, 100, size=10)
y = np.random.randint(1, 100, size=10)
corr = np.corrcoef(x, y)
print(corr)


[[ 1.         -0.33153219]
 [-0.33153219  1.        ]]


In [144]:
# Q64
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result_64 = np.dot(A, B)
print(result_64)


[[19 22]
 [43 50]]


In [145]:
# Q65
arr = np.random.randint(10, 1001, size=50)
p10 = np.percentile(arr, 10)
p50 = np.percentile(arr, 50)
p90 = np.percentile(arr, 90)
q1 = np.percentile(arr, 25)
q3 = np.percentile(arr, 75)
print(p10, p50, p90, q1, q3)


82.80000000000001 444.0 912.1 230.25 731.75


In [146]:
# Q66
arr = np.array([12, 25, 6, 42, 8, 30])
index = np.where(arr == 42)[0][0]
print(index)


3


In [147]:
# Q67
arr = np.random.randint(1, 100, size=10)
sorted_arr = np.sort(arr)
print(sorted_arr)


[ 1 17 20 25 31 48 53 65 80 95]


In [148]:
# Q68
arr = np.array([1, 5, 8, 12, 15])
result_68 = arr[arr > 20]
print(result_68)


[]


In [149]:
# Q69
arr = np.array([10, 20, 30, 40, 50])
result_69 = arr[arr % 3 == 0]
print(result_69)


[30]


In [150]:
# Q70
arr = np.array([10, 20, 30, 40, 50])
result_70 = arr[(arr >= 20) & (arr <= 40)]
print(result_70)


[20 30 40]


In [151]:
# Q71
arr = np.array([1, 2, 3])
byte_order = arr.dtype.byteorder
print(byte_order)


=


In [152]:
# Q72
import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap(inplace=True)
print(arr)


[16777216 33554432 50331648]


In [154]:
# Q75
arr = np.array([1, 2, 3], dtype=np.int32)
needs_swap = arr.dtype.byteorder not in ('=', '|')
print(needs_swap)
# Q73
arr = np.array([1, 2, 3], dtype=np.int32)
swapped = arr.newbyteorder()
print(swapped)


False


AttributeError: `newbyteorder` was removed from the ndarray class in NumPy 2.0. Use `arr.view(arr.dtype.newbyteorder(order))` instead.

In [155]:
# Q74
arr = np.array([1, 2, 3], dtype=np.int32)
if arr.dtype.byteorder == '=':
    swapped = arr.newbyteorder()

else:
    swapped = arr
print(swapped)


AttributeError: `newbyteorder` was removed from the ndarray class in NumPy 2.0. Use `arr.view(arr.dtype.newbyteorder(order))` instead.

In [156]:
# Q75
arr = np.array([1, 2, 3], dtype=np.int32)
needs_swap = arr.dtype.byteorder not in ('=', '|')
print(needs_swap)


False


In [157]:
# Q76
arr1 = np.arange(1, 11)
copy_arr = arr1.copy()
copy_arr[0] = 99
print(arr1)
print(copy_arr)


[ 1  2  3  4  5  6  7  8  9 10]
[99  2  3  4  5  6  7  8  9 10]


In [158]:
# Q77
matrix = np.random.randint(1, 100, size=(3, 3))
view_slice = matrix[:2, :2]
view_slice[0, 0] = -1
print(matrix)


[[-1  1 70]
 [59  9 47]
 [32 88 80]]


In [159]:
# Q78
array_a = np.arange(1, 13).reshape(4, 3)
view_b = array_a[1:3, :]
view_b += 5
print(array_a)


[[ 1  2  3]
 [ 9 10 11]
 [12 13 14]
 [10 11 12]]


In [160]:
# Q79
orig_array = np.arange(1, 9).reshape(2, 4)
reshaped_view = orig_array.reshape(4, 2)
reshaped_view[0, 0] = -5
print(orig_array)


[[-5  2  3  4]
 [ 5  6  7  8]]


In [161]:
# Q80
data = np.random.randint(1, 10, size=(3, 4))
data_copy = data[data > 5].copy()
data_copy[0] = -10
print(data)
print(data_copy)


[[6 1 7 2]
 [4 8 6 7]
 [8 9 2 7]]
[-10   7   8   6   7   8   9   7]


In [162]:
# Q81
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
add_result = A + B
sub_result = A - B
print(add_result)
print(sub_result)


[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]


In [163]:
# Q82
C = np.random.randint(1, 10, size=(3, 2))
D = np.random.randint(1, 10, size=(2, 4))
result_82 = np.dot(C, D)
print(result_82)


[[42 88 47 32]
 [61 85 38 45]
 [49 93 48 37]]


In [164]:
# Q83
E = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
transpose_E = E.T
print(transpose_E)


[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [165]:
# Q84
F = np.array([[6, 1], [4, 2]])
det_F = np.linalg.det(F)
print(det_F)


8.000000000000002


In [166]:
# Q85
G = np.array([[4, 7], [2, 6]])
inv_G = np.linalg.inv(G)
print(inv_G)


[[ 0.6 -0.7]
 [-0.2  0.4]]
